### ISSUE TITLE
Download takes a long time

### ISSUE THREAD

**Issue by BKSalman** [Mithronn/rusty_ytdl#1]
Hello!

I've come across your crate when I was searching for a replacement for ``yt-dlp`` in rust!

when I tried to use it, getting video info works, but actually downloading the video takes a very very long time,

I tried to track down the issue, and found it to be in the ``cut_after_js`` function in ``utils.rs``, it loops over a huge json string, and takes forever.

I think you're still figuring the download out, but I just wanted to file an issue to motivate you to try and tackle the issue :).

Thank you for your efforts!.

**Comment by Mithronn** [comment]
With version 0.4.1 I removed the use of the `cut_after_js` function in the `extract_ncode` function and the problem seems to be fixed. If you encounter the error again, feel free to reopen the issue.
