### ISSUE TITLE
Reusing a single reqwest client

### ISSUE THREAD

**Issue by AlvaroMS25** [Mithronn/rusty_ytdl#20]
Hello!

I'm testing out this crate for a project, and it seems it creates a new reqwest client for each video information i want to get, is there any way to just provide a reqwest client to each video / youtube search and reuse it?

**Comment by Mithronn** [comment]
implemented with `0.7.1`. You can find [examples](https://github.com/Mithronn/rusty_ytdl/tree/main/examples)
