### ISSUE TITLE
Playlist not retrieving videos

### ISSUE THREAD

**Issue by AlvaroMS25** [Mithronn/rusty_ytdl#21]
Hello! when i try to query a playlist, i don't seem to be able to retrieve the videos inside it, everything else works just fine, but the videos vector is empty, i'm using the `Youtube#search_one` method with the search type set to `Playlist`

sorry for the problems

**Comment by Mithronn** [comment]
@AlvaroMS25 Yes, search results do not include playlist videos. You need to perform a second request to get videos from the playlist

Example
```rust

    let search = youtube
        .search_one(
            "nightblue",
            Some(&SearchOptions {
                search_type: SearchType::Playlist,
                ..Default::default()
            }),
        )
        .await;

    match search.unwrap().unwrap() {
        rusty_ytdl::search::SearchResult::Playlist(raw_playlist) => {
            let mut playlist = Playlist::get(raw_playlist.url, None).await.unwrap();

            let playlist = playlist.fetch(None).await;

            println!("{:#?}", playlist.videos.len());
        }
        _ => unimplemented!(),
    }

```
