### ISSUE TITLE
[Question] How to use ffmpeg params to strip beginning of a video?

### ISSUE THREAD

**Issue by Timtam** [Mithronn/rusty_ytdl#22]
Hello there,

thanks again for the great work. It works just fine right now.
I noticed you adding ffmpeg args to the video downloader. I'm using ffmpeg-cli right now to process the downloaded video by converting it to mp3, which should be rather obvious to do with your ffmpeg args as well, but i'm also giving it the "-ss TIME" command line parameter to strip audio at the beginning of the video. Do your ffmpeg args support this too? If yes I could certainly drop ffmpeg-cli :).
Thanks again!

**Comment by Mithronn** [comment]
for now, only video and audio filters can be applied to video. Maybe in the future, I can implement other options like "-ss"
