### ISSUE TITLE
"extract_ncode" function error due to player yt changes

### ISSUE THREAD

**Issue by Timtam** [Mithronn/rusty_ytdl#27]
It currently looks like downloading through this package is broken. Downloading whichever link results in a 0 KB file, although rusty_ytdl considers the download successful. Maybe they changed something in the backend?
I tried well over 20 links and all of them end in the same way. Here is an example: https://www.youtube.com/watch?v=U_QeQVF8bRo

**Comment by HZzz2** [comment]
I have the same problem, the downloaded file is 0KB

**Comment by Mithronn** [comment]
It seems fixed with the latest release v0.7.3
