### ISSUE TITLE
Can't download a certain video

### ISSUE THREAD

**Issue by DCNick3** [Mithronn/rusty_ytdl#29]
For some reason, trying to download a certain video (https://www.youtube.com/watch?v=Y-3IV11_ZgA) doesn't work and fails with "Video is private" error. The video is, in fact, not private.

Latest `yt-dlp` (`2024.07.25`) successfully downloads it. Most other videos can also be downloaded fine with `rusty_ytdl`.

(Reproducible by `cargo run --release -p rusty_ytdl-cli download --id 'Y-3IV11_ZgA'` on c0175408ee26b8648e46c8a87eafb297920f1d8d)

**Comment by Mithronn** [comment]
@DCNick3 thanks for the feedback. I checked the video and it is an age-restricted video. With https://github.com/Mithronn/rusty_ytdl/commit/9ca056751dde6acbb2463e8de4b50c65083a6aca commit now you can call the `get_info` function without any error also if the video uploader has not disabled `allow embedding` option you can download too.
