### ISSUE TITLE
Feature request: allow retries for chunks

### ISSUE THREAD

**Issue by nick42d** [Mithronn/rusty_ytdl#32]
When looking to integrate the fix for the fix for #31 into my project, `youtui`, I noticed that even the individual chunks of a `Stream` can fail. To then retry streaming I need to start from the start again.

From what I can tell a simple way to resolve  could be the addition of a new `chunk_with_retries` method on the `Stream` trait, since the requests inside `NonLiveStream` and `LiveStream` seem on first glance to be repeatable.

Let me know your thoughts and I'm happy to have a go with a PR.

**Comment by Mithronn** [comment]
This crate already uses the `reqwest-retry` crate but it only retries for 500..599, 408, and 429 status codes. I will publish a new commit with a new strategy which includes 400..499 and 500..599. But feel free to make new PR maybe your solution would be better
