### ISSUE TITLE
bug: stream.chunk() don't working

### ISSUE THREAD

**Issue by KingTimer12** [Mithronn/rusty_ytdl#35]
I don't know why this happens, it worked months ago but suddenly it stopped working;

Code:
![image](https://github.com/user-attachments/assets/66216b91-6b34-4bec-9c2c-4d2e876c0b55)

Logs:
![image](https://github.com/user-attachments/assets/095d39c9-5b99-4cc4-95c9-8ab4f79083d0)

I tested using only stream and stream with ffmpg, I didn't check the download but as it uses the stream methods, I imagine you have the same problem;

The chunks in the while let are all returning 0

**Comment by Mithronn** [comment]
Crate 0.7.3 has not yet been updated in crates.io! You can use like that

```toml
rusty_ytdl = { git = "https://github.com/Mithronn/rusty_ytdl/", branch = "main"}
```

**Comment by KingTimer12** [comment]
Hum... Don't worked
![image](https://github.com/user-attachments/assets/7f7be77c-f21c-4e05-9a7d-f4b1054fc863)

**Comment by Mithronn** [comment]
see https://github.com/Mithronn/rusty_ytdl/issues/31#issuecomment-2265577102

**Comment by KingTimer12** [comment]
This error happened because I had outdated my tokio, when I returned it to version 1.9, it fixed the problem. The stream method works, but the one I need is `stream_with_ffmpeg`

But why with `stream_with_ffmpeg` dont work?

![image](https://github.com/user-attachments/assets/fc79bf5a-8ea2-45e8-8b88-a6d99ed6e01f)

![image](https://github.com/user-attachments/assets/d57c2ae4-e4c8-4359-8c1f-374cc87f5325)

**Comment by KingTimer12** [comment]
I take back what I said, the problem wasn't in my tokio, you're right, I'll be waiting for this problem to be fixed

**Comment by Mithronn** [comment]
Yeah as I said. Youtube sometimes giving error and sometimes not
