### ISSUE TITLE
Feature request: Take VideoOptions by reference

### ISSUE THREAD

**Issue by nick42d** [Mithronn/rusty_ytdl#38]
Just a small one, logging it whilst I remember.

Would be nice if `Video::new_with_options()` would take VideoOptions by reference.

I am storing my VideoOptions in a struct so I can re-use it when running concurrent downloads.

Happy to take a look and raise a PR if there are no technical issues.

**Comment by Mithronn** [comment]
There don't seem to be any technical problems. You can raise PR.
