### ISSUE TITLE
Error 403 forbidden on stream.chunk()

### ISSUE THREAD

**Issue by MalpenZibo** [Mithronn/rusty_ytdl#44]
I still get error 403 with every video that I have tried. I'm already using the latest commit on the main branch.

I see that this commit https://github.com/Mithronn/rusty_ytdl/commit/d4798aaab5d8079d8e0fd2a354325d65685a712f should have resolved the issue but in my case, the error persist.

**Comment by clytras** [comment]
@MalpenZibo I've had a similar issue, but it was due to `reqwest` custom features and missing `cookies` feature.
There must be an issue with `reqwest` and its' features, but I can't dig more on it now.

**Comment by nick42d** [comment]
> @MalpenZibo I've had a similar issue, but it was due to `reqwest` custom features and missing `cookies` feature. There must be an issue with `reqwest` and its' features, but I can't dig more on it now.

Are you providing cookies to the client with that feature? If so, where do you get them from?
