### ISSUE TITLE
Segfault when running multiple times `let info = video.get_info().await?;` in a row, in a tokio task

### ISSUE THREAD

**Issue by ccgauche** [Mithronn/rusty_ytdl#9]
Here is a minimal reproducible example:
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    tokio::spawn(async move {
            let video_options = VideoOptions::default();
            let video = Video::new_with_options("3OAwbY-rKRw", video_options).unwrap();
            let _ = video.get_info().await.unwrap();
            let _ = video.get_info().await.unwrap();
            let _ = video.get_info().await.unwrap();
            println!("ok");
        
    }).await.unwrap();
    Ok(())
}
```

**Comment by nick42d** [comment]
@ccgauche love your work on Ytermusic! I am working on a similar project and have run into the same error and so may have some useful information:

1. Error occurred for me on Pop_os! but not EndeavourOS
2. Core dump on Pop_os! produces the below trace back to v8 source.

`Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000556c0810aab3 in v8::internal::ThreadIsolation::UnregisterJitPage(unsigned long, unsigned long, --Type <RET> for more, q to quit, c to continue without paging--
v8::internal::ThreadIsolation::AllocationSource) ()
    at ../../../../v8/src/common/code-memory-access.cc:364
364	../../../../v8/src/common/code-memory-access.cc: No such file or directory.
[Current thread is 1 (Thread 0x7ff36c7f4640 (LWP 40954))]`

**Comment by ccgauche** [comment]
I managed to fix the issue I'll make a PR you can always use my fork that fixes the issue

**Comment by Mithronn** [comment]
@ccgauche i saw your fork and **boa_engine** is more stable than **js-sandbox**! I will implement with the new release 0.6.5! Thanks for the fork.
